-- =====================================================================================
-- The two accounts a realm needs that no player creates: the auction house bot's, and one
-- to test with.
--
-- GENERATED by scratchpad/make_accounts.py (it computes the SRP6 verifier). Regenerate
-- rather than editing the hash by hand.
--
-- Applied automatically: it lives in data/sql/custom/db_world, one of the directories
-- AzerothCore's updater scans, so a realm built from zero has both accounts before
-- RandomPlayerbotMgr creates its first bot. Editing it changes the file's hash, which is what
-- makes the updater run it again.
--
-- Fully-qualified table names, so the selected database does not matter. Re-runnable: every
-- statement is an INSERT ... ON DUPLICATE KEY UPDATE or is guarded, so applying it by hand
-- works too:
--
--     mysql -uacore -pacore < realm_accounts.sql
--
-- A restart is still needed before the AH bot USES any of it: AuctionHouseBot.Account and
-- .GUID are read only at startup.
--
-- -------------------------------------------------------------------------------------
-- WHY THESE IDS
--
-- mod-playerbots creates its accounts by NAME (AiPlayerbot.RandomBotAccountPrefix,
-- "rndbot") and lets MySQL assign the id, so neither name below can ever collide. It does
-- claim accounts permanently in acore_playerbots.playerbots_account_type keyed by ID, which
-- is what once made it log the AH bot in as a bot with no AI -- hence the explicit high ids
-- and the guard at the end.
--
-- Inserting an explicit id raises the table's AUTO_INCREMENT, so bot accounts created after
-- this file continue from 1002 rather than 53. Nothing depends on account ids being small.
--
-- -------------------------------------------------------------------------------------
-- WHY THE AH BOT'S CHARACTER GUID IS 999000
--
-- Not 1: on a realm built from zero, guid 1 belongs to a random bot character that the bot
-- manager created and is actively using. The previous version of this file assumed guid 1
-- was the AH bot's -- true on the old realm, where the character predated the bot pool --
-- and carried an ON DUPLICATE KEY UPDATE that would have taken that bot's character over.
--
-- Not max(guid)+1 either. A running worldserver has already reserved its character-guid
-- generator from the maximum it saw at startup, so inserting just above the current maximum
-- is exactly where it will hand out the next guid -- a duplicate key waiting to happen. A
-- guid far outside the range keeps this insertable while the server runs. After the next
-- restart the generator resumes above it; ids being large costs nothing.
-- =====================================================================================

-- --- 1. the auction house bot ----------------------------------------------------------
-- Deliberately NOT loginable: zeroed salt and verifier. The account exists so the auctions
-- have an owner, and nobody should be able to sign in as it.
INSERT INTO `acore_auth`.`account` (`id`, `username`, `salt`, `verifier`, `email`, `reg_mail`, `expansion`) VALUES
(1000, 'AHBOT',
 0x0000000000000000000000000000000000000000000000000000000000000000,
 0x0000000000000000000000000000000000000000000000000000000000000000,
 '', '', 2)
ON DUPLICATE KEY UPDATE `expansion` = 2;

-- The character the auctions are posted by. It never logs in, so a minimal row is enough --
-- every other column has a usable default. Position is Northshire, which is only where it
-- would appear if anyone ever did log it in.
INSERT INTO `acore_characters`.`characters`
(`guid`, `account`, `name`, `race`, `class`, `gender`, `level`, `money`,
 `position_x`, `position_y`, `position_z`, `map`, `orientation`,
 `taximask`, `cinematic`, `health`, `power1`, `innTriggerId`) VALUES
(999000, 1000, 'AHBot', 1, 1, 0, 1, 0,
 -8949.95, -132.493, 83.5312, 0, 0,
 '0', 1, 60, 100, 0)
ON DUPLICATE KEY UPDATE `account` = 1000, `name` = 'AHBot';

-- --- 2. the tester -----------------------------------------------------------------------
-- Loginable. SRP6 verifier for user 'TESZT', password 'teszt' -- to change the
-- password, edit GM_PASS in scratchpad/make_accounts.py and re-run it, or use
-- `account set password` from the worldserver console.
INSERT INTO `acore_auth`.`account` (`id`, `username`, `salt`, `verifier`, `email`, `reg_mail`, `expansion`) VALUES
(1001, 'TESZT', 0x5445535A54204750202D20436C6173734C6573732074657374207265616C6D21, 0x2E3ADD4BB0D1501F501DF6D9BF1841B76734ED2FDE358707E213C0392D893F74, '', '', 2)
ON DUPLICATE KEY UPDATE `salt` = 0x5445535A54204750202D20436C6173734C6573732074657374207265616C6D21, `verifier` = 0x2E3ADD4BB0D1501F501DF6D9BF1841B76734ED2FDE358707E213C0392D893F74, `expansion` = 2;

-- gmlevel 3 is SEC_ADMINISTRATOR: every command, including the ones that rewrite character
-- state. RealmID -1 means "on every realm" rather than only realm 1.
INSERT INTO `acore_auth`.`account_access` (`id`, `gmlevel`, `RealmID`, `comment`) VALUES
(1001, 3, -1, 'ClassLess test account')
ON DUPLICATE KEY UPDATE `gmlevel` = 3;

-- --- 3. the dungeon-clear test driver ----------------------------------------------------
-- `.dc test` issued from the console or over SOAP has no in-game player to anchor the run on,
-- so mod-dungeon-clear logs in a stand-in of its own -- the character named by
-- DungeonClear.TestRun.DriverCharacter -- and parks it. It does not create that character;
-- DcTestDriver::Ensure just reports "not found" and refuses the run.
--
-- Its account must not be a random-bot or addclass-pool account, or the bot rotation would
-- claim the character and drive it. Reserved id, like the two above, and kept out of
-- playerbots_account_type by section 4.
--
-- Not loginable (zeroed salt and verifier): the module logs it in server-side through
-- RandomPlayerbotMgr::AddPlayerBot, which needs no password.
INSERT INTO `acore_auth`.`account` (`id`, `username`, `salt`, `verifier`, `email`, `reg_mail`, `expansion`) VALUES
(1002, 'DCDRIVER',
 0x0000000000000000000000000000000000000000000000000000000000000000,
 0x0000000000000000000000000000000000000000000000000000000000000000,
 '', '', 2)
ON DUPLICATE KEY UPDATE `expansion` = 2;

-- Unlike the AH bot's character this one really enters the world, so it needs a homebind row
-- as well -- Player::LoadFromDB fails the login without one. Human warrior in Northshire.
INSERT INTO `acore_characters`.`characters`
(`guid`, `account`, `name`, `race`, `class`, `gender`, `level`, `money`,
 `position_x`, `position_y`, `position_z`, `map`, `orientation`,
 `taximask`, `cinematic`, `health`, `power1`, `innTriggerId`) VALUES
(999001, 1002, 'Dcdriver', 1, 1, 0, 1, 0,
 -8949.95, -132.493, 83.5312, 0, 0,
 '0', 1, 60, 100, 0)
ON DUPLICATE KEY UPDATE `account` = 1002, `name` = 'Dcdriver';

INSERT INTO `acore_characters`.`character_homebind` (`guid`, `mapId`, `zoneId`, `posX`, `posY`, `posZ`) VALUES
(999001, 0, 12, -8949.95, -132.493, 83.5312)
ON DUPLICATE KEY UPDATE `mapId` = 0, `zoneId` = 12;

-- --- 4. put the id counter past them ------------------------------------------------------
-- mod-playerbots creates its accounts by name and lets MySQL assign the id, walking up from
-- wherever AUTO_INCREMENT currently sits. Inserting explicit ids above it does not move it,
-- so a pool that grows far enough eventually tries to insert id 1000, finds this row, and
-- fails on the duplicate key -- bot account creation stops, and the only sign is an error in
-- a log nobody reads. Moving the counter past both reserved ids costs nothing: account ids
-- carry no meaning beyond being unique.
ALTER TABLE `acore_auth`.`account` AUTO_INCREMENT = 2000;

-- --- 5. keep the bot manager off all three ------------------------------------------------
-- Nothing should have claimed these -- the pool grows by name, not by id -- but a stale claim
-- here is invisible until the AH bot starts being logged in as a bot with no AI.
--
-- Wrapped, because acore_playerbots is updated AFTER acore_world: on a realm built from zero
-- that table does not exist while this runs, and a plain DELETE would abort the whole file --
-- taking the two accounts above with it, on exactly the run that was supposed to create them.
SET @has_bots := (SELECT COUNT(*) FROM `information_schema`.`TABLES`
                  WHERE `TABLE_SCHEMA` = 'acore_playerbots'
                    AND `TABLE_NAME` = 'playerbots_account_type');
SET @stmt := IF(@has_bots > 0,
    'DELETE FROM `acore_playerbots`.`playerbots_account_type` WHERE `account_id` IN (1000, 1001, 1002)',
    'DO 0');
PREPARE drop_claims FROM @stmt;
EXECUTE drop_claims;
DEALLOCATE PREPARE drop_claims;
